name: niku
description: Property builder for styling Widget with SwiftUI like pattern
version: 2.0.0-experimental.0
homepage: https://github.com/saltyAom/niku

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  union: ^0.0.4-nullsafety.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
