name: niku
description: Property builder for styling Widget with SwiftUI like pattern
version: 0.5.1
homepage: https://github.com/saltyAom/niku

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
