name: niku
description: Property builder for styling Widget with SwiftUI like pattern
version: 2.0.0-experimental.3
homepage: https://github.com/saltyAom/niku

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
