name: niku
description: Property builder for styling Widget with SwiftUI like pattern
version: 2.1.0
homepage: https://github.com/saltyAom/niku

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.15.0
  # Wait until cached network image support web platform
  # cached_network_image: ^3.2.0
  # flutter_cache_manager: ^3.3.0
  # cached_network_image_platform_interface: ^1.0.0
  # cached_network_image_web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
